# Generated by Django 3.2.7 on 2021-12-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211209_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_profile_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
