# Generated by Django 3.2.7 on 2021-12-23 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211220_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
    ]
