# Generated by Django 3.2.7 on 2021-12-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_blocked_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blocked_user',
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='_account_user_blocked_user_+', to='account.User'),
        ),
    ]
