# Generated by Django 3.2.7 on 2021-12-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211223_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blocked_user',
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(related_name='_account_user_blocked_users_+', to='account.User'),
        ),
    ]
