# Generated by Django 3.2.7 on 2021-12-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20211223_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='_account_user_blocked_users_+', to='account.User'),
        ),
    ]
