# Generated by Django 3.2.7 on 2022-01-01 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_blockandreportmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockandreportmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='blockandreportmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
    ]
