# Generated by Django 3.2.7 on 2022-01-01 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_remove_postmodel_likes'),
        ('account', '0010_auto_20220101_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockandreportmodel',
            name='report_on_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_reported', to='Post.postmodel'),
        ),
        migrations.AlterField(
            model_name='blockandreportmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_report', to='account.user'),
        ),
    ]
