# Generated by Django 3.2.7 on 2022-01-01 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20220101_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockandreportmodel',
            old_name='user',
            new_name='reported',
        ),
        migrations.AddField(
            model_name='blockandreportmodel',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='account.user'),
        ),
    ]
