# Generated by Django 4.0 on 2022-01-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_relationmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelationModel',
            new_name='RelationFollowingModel',
        ),
    ]
