# Generated by Django 3.2.7 on 2021-12-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_postmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
