# Generated by Django 3.2.7 on 2021-12-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_postmodel_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='time',
        ),
    ]
