# Generated by Django 3.2.7 on 2021-12-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_likepostmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikePostModel',
        ),
    ]
