# Generated by Django 3.2.7 on 2022-01-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_remove_postmodel_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addres', models.GenericIPAddressField()),
            ],
        ),
    ]
