# Generated by Django 3.2.7 on 2022-01-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_ipaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipaddress',
            old_name='ip_addres',
            new_name='ip_address',
        ),
    ]
