# Generated by Django 3.2.7 on 2022-01-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0010_rename_ip_addres_ipaddress_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='views',
            field=models.ManyToManyField(blank=True, null=True, to='Post.IPAddress'),
        ),
    ]
