# Generated by Django 3.2.7 on 2022-01-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0011_postmodel_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='views',
            field=models.ManyToManyField(blank=True, to='Post.IPAddress'),
        ),
    ]
