# Generated by Django 4.0 on 2022-01-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0015_likemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/image/'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='video',
            field=models.FileField(blank=True, upload_to='media/video/'),
        ),
    ]
