# Generated by Django 4.0 on 2022-01-18 19:24

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0017_alter_postmodel_image_alter_postmodel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/', validators=[Post.models.image_size]),
        ),
    ]
