# Generated by Django 4.0 on 2022-01-23 21:28

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0018_alter_postmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='video',
            field=models.FileField(blank=True, upload_to='video/', validators=[Post.models.video_size]),
        ),
    ]
